version: '2'
services:
  slow-web:
    container_name: slow-web
    image: "nginx:alpine"
    ports:
      - "8080:8080"
    volumes:
      - ../www:/www
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
